### ISSUE TITLE
Container does not have write access to /config/

### ISSUE THREAD

**Issue by slimcdk** [thomasloven/hass-custom-devcontainer#41]
How do you overcome this issue?

```bash
Configuration file: True
Creating Home Assistant User mitblod:dev
Traceback (most recent call last):
  File "/usr/local/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/homeassistant/__main__.py", line 286, in main
    return scripts.run(args.script)
  File "/usr/local/lib/python3.8/site-packages/homeassistant/scripts/__init__.py", line 67, in run
    return script.run(args[1:])  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/homeassistant/scripts/auth.py", line 48, in run
    asyncio.run(run_command(parser.parse_args(args)))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/homeassistant/scripts/auth.py", line 58, in run_command
    await args.func(hass, provider, args)
  File "/usr/local/lib/python3.8/site-packages/homeassistant/scripts/auth.py", line 86, in add_user
    await provider.data.async_save()
  File "/usr/local/lib/python3.8/site-packages/homeassistant/auth/providers/homeassistant.py", line 213, in async_save
    await self._store.async_save(self._data)
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/storage.py", line 154, in async_save
    await self._async_handle_write_data()
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/storage.py", line 224, in _async_handle_write_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/homeassistant/helpers/storage.py", line 233, in _write_data
    os.makedirs(os.path.dirname(path))
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/config/.storage'
/usr/bin/container: line 17: /config/.storage/onboarding: No such file or directory
INFO: Trying to find the correct directory...

ERROR: Could not find the directory for Home Assistant
Manually change the directory to the root of your Home Assistant configuration
With the user that is running Home Assistant
and run the script again
/usr/bin/container: line 65: /config/.storage/lovelace_resources: No such file or directory
/usr/bin/container: line 89: /config/.storage/lovelace_resources: No such file or directory
[4828 ms] Error: Command failed: /bin/sh -c container setup && npm add
        at ag (/home/christian/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:169:15)
        at async rg (/home/christian/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:163:2458)
        at async /home/christian/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:145:7537
```
This is my `devcontainer.json` file and corrosponding source code in the repository 
https://github.com/slimcdk/homeassistant-mitblod/blob/master/.devcontainer/devcontainer.json

I have also tried without having the hacs mount added as well as not having any mounts. Got same error.

**Comment by slimcdk** [comment]
Prepending `sudo chown -R vscode /config` to the post create command seems to work.

Closing.
